trigger:
  - master
  - develop


variables:
  buildConfiguration: 'DEBUG'


strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
    macos:
      imageName: 'macos-10.15'
    windows:
      imageName: 'windows-2019'


pool:
  vmImage: $(imageName)


steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore $(buildConfiguration)'
    inputs:
      command: restore
      arguments: '--configuration $(buildConfiguration)'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build $(buildConfiguration)'
    inputs:
      command: build
      arguments: '--configuration $(buildConfiguration)'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: test
      arguments: '--configuration $(buildConfiguration) --verbosity normal'
      projects: '**/*Test/*.csproj'
