scheme = "Monochrome"
style = "Powerline"

[default]
separator_right = ""
separator_left = ""
terminator_right = ""
terminlator_left = ""
git_branch = ""
git_stash = "▣"
git_ahead = "▲"
git_behind = "▼"
git_ahead_behind = "◆"
git_identical = "≡"
git_add = "+"
git_remove = "-"
git_modify = "~"
git_conflict = "!"
not_git = "?"
venv_dart = ""
venv_dotnet = ""
venv_elixir = ""
venv_kotlin = ""
venv_python = ""
venv_ruby = ""
venv_scala = ""
vnev_rust = ""

[terminal]
# decor8r config prompt show [prompt|rprompt|cprompt|dprompt]
prompt = [ "ssh", "mode", "user", "path", "git", "pipe", "status"]
right_prompt = []
continue_prmpt = ["continue"]
debug_prompt = []
compress = ["path", "git"]
compress_mode = "elison"

[terminal.ssh]

[nvim]
status_line = ["mode", "file"]
rstatus_line = ["cursor", "percentage", "encoding", "lineterminator"]
tab_line = ["file", "buffer"]

[tmux]
status_line = ["session", "tabs"]
rstatus_line = ["host", "time", "date", "load", "uptime", "venv"]

[[schemes]]
name = "Monochrome"

[[schemes]]
name = "Base16"

[[styles]]
name = "Basic"

[[styles]]
name = "Powerline"

[[styles]]
name = "AxlER8R"
