#! /usr/bin/env zsh

GITHUB_DIR="~/Projects/GitHub"
if [[ -d ${GITHUB_DIR} ]]
then
    pushd -q ${GITHUB_DIR}
    rm -rf go-app-powerline
    rm -rf microsoft-pwsh-extension-ohmyposh
    rm -rf microsoft-pwsh-extension-poshgit
    rm -rf python-app-powerline
    rm -rf rust-app-starship
    popd -q
fi
