#! /usr/bin/zsh

_DOTNET_BASE=$(dotnet --info | grep "Base Path" | awk '{print $3}')
echo "DOTNET_BASE: ${_DOTNET_BASE}"

_DOTNET_ROOT=$(echo "${_DOTNET_BASE}" | sed -E "s/^(.*)(\/sdk\/[^\/]+\/)$/\1/")
echo "DOTNET_ROOT: ${_DOTNET_ROOT}"

export MSBuildSDKsPath="${_DOTNET_BASE}Sdks/"
export DOTNET_ROOT="${_DOTNET_ROOT}"
export path=("${_DOTNET_ROOT}" $path)

